AWSTemplateFormatVersion: 2010-09-09
Resources:
  HYFBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', ['hyf-week1-cf',!Ref 'AWS::StackName']]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
